# Number of items the player will receive per minute
ItemsPerMinute: 3
# Max Number of items the player can receive per minute
MaxItemsPerMinute: 30
# Worlds where the plugin is currently active
ActiveWorlds:
  -world
  -world_nether
  -world_the_end